### ISSUE TITLE
Removal of ACF Options page

### ISSUE THREAD

**Issue by c-fitzmaurice** [wordplate/acf#16]
Hello!

I see [here](https://github.com/wordplate/acf/commit/fb56f3c05d62927246e7026366be07bb4563780a) that you removed the options page from the docs but it seems to still be operational in the code. Are there plans to remove it all together? I want to use it, but want to make sure it will still be around soon.

Thanks for the package...love it!

**Comment by vinkla** [comment]
Hey!

I'm glad you like the package! Actually, we decided to remove the `acf_page` helper since it is just a wrapper around `acf_add_options_page`. If you replace `acf_page` with `acf_add_options_page` everything should work as before.

**Comment by c-fitzmaurice** [comment]
Thank you!
