### ISSUE TITLE
Add the ability to hide the wordpress default fields 

### ISSUE THREAD

**Issue by MarlBurroW** [wordplate/acf#17]
For me, the most missing feature is the ability to hide wordpress default fields (WYSIWYG Editor, pemarlinks, author, excerpt, etc...) from your API exactly like the ACF UI.

**Comment by vinkla** [comment]
Thanks for the feedback! This is actually already included, you may add the `hide_on_screen` option when registering a new field group:

```php
acf_field_group([
    'title' => 'About',
    'fields' => $fields,
    'style' => 'seamless',
    'location' => $location,
    'hide_on_screen' => ['the_content', 'author'],
]);
```

**Comment by MarlBurroW** [comment]
Oh cool, didn't find it in the README.md.

Thank you very much.

**Comment by vinkla** [comment]
> Oh cool, didn't find it in the README.md.

Feel free to add it! We'll look at any pull request you send our way.
