### ISSUE TITLE
ACF 5.8 – Introducing ACF Blocks for Gutenberg - any changes?

### ISSUE THREAD

**Issue by symbioticwp** [wordplate/acf#31]
Hi,

I open this issue according to this blog post: [ACF 5.8 – Introducing ACF Blocks for Gutenberg](https://www.advancedcustomfields.com/blog/acf-5-8-introducing-acf-blocks-for-gutenberg/).

So will wordplate acf still work with this update. Has anybody tested it yet?

Regards!

**Comment by vinkla** [comment]
👋 ACF 5.8 is yet to be released. We've tried running this plugin on WordPress 5.0 without any issues. If you find any issues after you've upgraded, please open an issue GitHub.
