### ISSUE TITLE
Update 5 to 6

### ISSUE THREAD

**Issue by MaximVanhove** [wordplate/acf#33]
Updating from wordplate/acf 5 to 6 breaks te retrieving of data in the front end.

The fields are displayed in the backoffice though. This can be solved be republishing all posts, but this is an impossible job if we have more than 10.000 posts / pages.

**Comment by vinkla** [comment]
Yes, this is expected behaviour. 6.0 is basically a complete rewrite to come more inline with the ACF plugin settings and adding support for features such as the clone field.

If you aren't planing on using the clone field you should be fine staying on version 5.0.
