### ISSUE TITLE
Conditional.php generates wrong field name

### ISSUE THREAD

**Issue by MaximVanhove** [wordplate/acf#4]
I wanted to add conditional logic, but failed to do so.

This is my set up:

```php
//
// News / Blog items
//
$fields = [
    acf_image([
        'name' => 'banner',
        'label' => 'Banner',
        'wrapper' => ['width' => '100%'],
    ]),
    acf_radio([
        'name' => 'thumbnail_options',
        'label' => 'Image or video on thumbnail', 
        'wrapper' => ['width' => '100%'],
        'choices' => ['image' => 'Image',  'youtube' => 'Youtube'],
        'default_value' => '',
        'layout' => 'horizontal',
        'return_format' => 'value',
    ]),
    acf_image([
        'name' => 'thumbnail_image', 
        'label' => 'Thumbnail image', 
        'wrapper' => ['width' => '50%'],
        'conditional_logic' => array(
            array(
                array(
                    'name' => 'thumbnail_options',
                    'operator' => '==',
                    'value' => 'image',
                ),
            ),
        ),
    ]),
    acf_url([
        'name' => 'thumbnail_video',
        'label' => 'Thumbnail video',
        'wrapper' => ['width' => '50%'],
        'conditional_logic' => array(
            array(
                array(
                    'name' => 'thumbnail_options',
                    'operator' => '==',
                    'value' => 'youtube',
                ),
            ),
        ),
    ]),
];

$location = [
    [
        acf_location('post_type', 'post')
    ],
];

acf_field_group([
    'title' => 'News settings',
    'key' => 'group_news',
    'fields' => $fields,
    'style' => 'default',
    'location' => $location,
    'position' => 'normal',
    'hide_on_screen' => ['featured_image', 'categories'],
]);
```

It only works if I disable the logic in Conditional.php and change the config like this:

```
array(
    'field' => 'field_news_thumbnail_options',
    'operator' => '==',
    'value' => 'image',
),
```

**Comment by vinkla** [comment]
Hmm, have you tried using the `acf_conditional_logic` function?

**Comment by MaximVanhove** [comment]
I did, but this helper only returns the array I have above:

`acf_conditional_logic('thumbnail_options', 'image')`

returns

```
[
    "name" => "thumbnail_options"
    "operator" => "=="
    "value" => "image"
]
```

I think the real issue lays in Conditional.php or Field.php

**Comment by vinkla** [comment]
What version of this package and PHP are you using?

**Comment by MaximVanhove** [comment]
wordplate/acf: 3.1.0
advanced-custom-fields/advanced-custom-fields-pro: 5.5.14
php: 7.1.0

**Comment by MaximVanhove** [comment]
I created a pull request with a possible fix

**Comment by vinkla** [comment]
Thanks, I'll look into this as soon as I've time to spare!

**Comment by vinkla** [comment]
@MaximVanhove thanks for reporting! I've pushed a fix in f3eb02c65d7961b927a64d4442c83edb96f92e75.

Are you your code in production yet? If not, you could upgrade to the latest beta version 4.0.

**Comment by MaximVanhove** [comment]
No it's still in progress. I'll test the beta soon. Thanks for the great work.

**Comment by vinkla** [comment]
> No it's still in progress. I'll test the beta soon. Thanks for the great work.

Okay, great! Just know that the new version is hashing the keys. This means data will be lost but if this is only in a development environment it should be too much of an issue.

**Comment by MaximVanhove** [comment]
I can confirm that this is fixed in 4.0 and no data is lost, but you need to save everything again first.

**Comment by vinkla** [comment]
Okay, great! Thanks for letting us know.

**Comment by vinkla** [comment]
Please take note of this breaking change in version 4.0: 6b8dd35c21563085da11427b467918a4c5b7daa1

**Comment by vinkla** [comment]
FYI I've pushed a new major version which generates shorter hashed and fixes an issue with the conditional logic keys.
