### ISSUE TITLE
returnFormat on ButtonGroup not working

### ISSUE THREAD

**Issue by asha23** [wordplate/acf#51]
## Expected Behavior

the returnFormat should be a field on ButtonGroup.

## Actual Behavior

Causes an error: 

```Call to undefined method WordPlate\Acf\Fields\ButtonGroup::returnFormat()```

## Steps to Reproduce the Problem

  1. Create a ButtonGroup
  2. add ```->returnFormat('value')```

### EG:

```
use WordPlate\Acf\Fields\ButtonGroup;

ButtonGroup::make('My Button', 'my_button')
    ->instructions("I am a button group")
    ->choices([
        0 => 'Show',
        1 => 'Hide'
    ])
    ->wrapper([
       'width' => '33%',
       'class' => '',
       'id' => '',
    ])
    ->returnFormat('value')

```

## Versions

  - WordPlate: 8.1.1
  - PHP: 7.2

**Comment by vinkla** [comment]
Thanks for reporting Ash! I've released an update in version 8.2.0.
