### ISSUE TITLE
Remove hack from Layout trait

### ISSUE THREAD

**Issue by szepeviktor** [wordplate/acf#53]
```php
$key = __CLASS__ === 'WordPlate\Acf\Fields\Layout' ? 'display' : 'layout';
```

This is a big hack 😿 and not testable.

Please have two different traits instead: Layout and Display.

**Comment by vinkla** [comment]
Feel free to send us a pull request to fix this. I would probably move create a second trait called `Display` in this case. Or add the layout method to the `Layout` class.

**Comment by vinkla** [comment]
> This is a big hack 😿 and not testable.

I'm curious, please give more context.

**Comment by szepeviktor** [comment]
I've ran static analysis on your code powered by @phpstan
It tracks e.g variable types and conditions.
The above conditions `__CLASS__ === 'WordPlate\Acf\Fields\Layout'` is always true for one class and always false for the other, so it generates analysis errors.

Plus - I think - doing two things in one method is not the greatest OOP code.

**Comment by vinkla** [comment]
Oh, so it is a limitation of PHPStan then.

Please let me know you'll send a pull request or else I'll close this.

**Comment by szepeviktor** [comment]
You were right.
It is a bug. See the issue over at PHPStan.

**Comment by vinkla** [comment]
Good catch 🙌 I’ll go ahead and close this.
